nav:
  Home: /
  About: /about/
  Writing: /archives/
  Projects: http://github.com/gjbianco

projects_url: http://github.com/gjbianco

customize:
  gravatar:
    email: gjbiancoiv@gmail.com
  logo:
    enabled: true
    width: 50
    height: 50
    url: /images/logo.jpg
    gravatar: true
  # favicon: 
  # eg. generate with http://realfavicongenerator.net/
  # desktop:
  #   url: /images/favicon.ico
  #   gravatar: false
  social_links:
    github: http://github.com/gjbianco
    twitter: http://twitter.com/gjbiancoiv
    linkedin: http://linkedin.com/in/gjbiancoiv
  show_all_posts: false
  post_count: 5
  highlight: rainbow

# RSS
rss: false

# Plugins
plugins:
  disqus_shortname: # Disqus Comments Shortname

# Miscellaneous
miscellaneous:
  open_graph: # see http://ogp.me
    fb_app_id:
    fb_admins:
    twitter_id:
    google_plus:
